plsv:
  target: host
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5431
      dbname: postgres
      schema: public
      threads: 3
      keepalives_idle: 0
      connect_timeout: 10 # default 10 seconds
    host:
      type: postgres
      host: localhost
      user: postgres
      password: '1'
      port: 5432
      dbname: postgres
      schema: dbt_crimespread
      threads: 3
      keepalives_idle: 0
      connect_timeout: 10 # default 10 seconds      
