plsv:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5431
      dbname: postgres
      schema: dbt_crimespread
      threads: 3
      keepalives_idle: 0
      connect_timeout: 10 # default 10 seconds
